name: .NET nuget publish

on:
  release:
    types: released

jobs:
  nugetpush:
    name: Build, test and push to nuget
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: | 
            8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish to Nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.nuget_apikey }} -s https://api.nuget.org/v3/index.json
    - name: Add Github Packages source
      run: dotnet nuget add source --username cmdotcom --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cmdotcom/index.json"
    - name: Publish to Github Packages
      run: dotnet nuget push **/*.nupkg -s github
